export const PATHS = {
  _selected: "/selected",
  availableKit: "/available",
  checkout: "/checkout",
  faq: "/faq",
  instruction: "/instruction",
  orderError: "/order_error",
  orderPaid: "/order_paid",
  orderSuccess: "/order_success",
  paymentInfo: "/payment-info",
  product: "/kits/:uid",
  root: "/",
  selectedKit: "/selected/:uid",
  tubes: "/tubes",
};
