export const API_ENDPOINTS = {
  ANALYSIS: "/analyses",
  KITS_LIST: "/kits",
  LABS_LIST: "/labs",
  LOGIN: "/auth/token",
  ORDERS_CURRENT: "/orders/current/submit-details",
  ORDERS_CURRENT_ANALYSES: "/orders/current/link-analyses",
  ORDERS_CURRENT_INSTRUCTIONS: "/orders/current/instructions",
  ORDERS_CURRENT_NUMBER: "/orders/current/number",
  ORDERS_CURRENT_PROGRESS: "/orders/current/progress",
  OTP: "/otp/send",
  OTP_CONFIRM: "/otp/confirm",
  PAYMENT_CANCEL: "/payments/cancel",
  PAYMENT_NOTIFY: "/payments/notify",
  PAYMENT_SESSION: "/payments/current/session",
  PAYMENT_SUCCESS: "/payments/success",
  REFRESH_TOKEN: "/auth/token/refresh",
  TUBES: "/tubes/link",
  TUBES_REQ: "/tubes/required",
  VERIFY_TOKEN: "/auth/token/verify",
};
